### ISSUE TITLE
Security Vulnerabilities reported on java minimal images

### ISSUE THREAD

**Issue by anokun7** [google/bazel_rules_install#30]
We are seeing multiple Critical and High severity vulnerabilities in the java images, in both version 8 & 11.

They appear to be in glibc, libpng & libjpeg-turbo packages. Below is the image scanning report from Docker hub.
![image](https://user-images.githubusercontent.com/1811413/101993930-61dea000-3c8c-11eb-90e8-5ee748f69af0.png)

![image](https://user-images.githubusercontent.com/1811413/101993810-8e45ec80-3c8b-11eb-91c9-8ca8e84b6467.png)

![image](https://user-images.githubusercontent.com/1811413/101993885-eed52980-3c8b-11eb-87ff-6a2afeaa7c19.png)
![image](https://user-images.githubusercontent.com/1811413/101993889-fa285500-3c8b-11eb-873e-cef22c9a4eed.png)

An online search reveals that there are newer versions of these packages available. But I am not sure how to update the packages inside the base images, or if there is an alternative to addressing these security findings.

**Comment by hzeller** [comment]
This looks like the reported issue is not related at all with this project ?
