### ISSUE TITLE
New owner needed

### ISSUE THREAD

**Issue by bttk** [google/bazel_rules_install#38]
I can no longer do any maintenance on this repo.

**Comment by hzeller** [comment]
I am sorry to hear that.

I can tentatively step in, though all of my expertise is only on Linux, not Windows or Mac where potentially future improvements might be.

 I also would like to nominate @QuantamHD who knows bazel well.

(I am [using](https://github.com/chipsalliance/verible/blob/master/BUILD#L42) the installer in [Verible](https://github.com/chipsalliance/verible))

**Comment by bttk** [comment]
Thanks @hzeller! Is there some additional access I could get at this time? Like being able to close an open issue.

**Comment by hzeller** [comment]
Once I get access myself, that can be done. Stay tuned.

**Comment by hzeller** [comment]
I sent an invite.

**Comment by bttk** [comment]
Thanks! Now that you have access, should we close this issue?

**Comment by hzeller** [comment]
Yes :)
